mandelbrot: fractal.cpp 
	g++ fractal.cpp -o mandelbrot -lsfml-graphics -lsfml-window -lsfml-system

carpet: sierpinski_carpet.cpp 
	g++ sierpinski_carpet.cpp -o sierpinski_carpet -lsfml-graphics -lsfml-window -lsfml-system

vulkan: vulkan_hello.cpp
	g++ vulkan_hello.cpp -o vulkan_hello -lvulkan